<?php

namespace Database\Seeders;

use App\Models\Option;
use Illuminate\Database\Seeder;

class OptionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::statement('SET FOREIGN_KEY_CHECKS=0');

        \DB::table('options')->delete();

        \DB::table('options')->insert([
            [
                'id' => 1,
                'option_id' => NULL,
                'nombre' => 'Dashboard',
                'ruta' => 'dashboard',
                'descripcion' => NULL,
                'icono_l' => 'fa-chart-line',
                'icono_r' => NULL,
                'orden' => 0,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 2,
                'option_id' => NULL,
                'nombre' => 'Admin',
                'ruta' => '',
                'descripcion' => NULL,
                'icono_l' => 'fa-tools',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 3,
                'option_id' => 2,
                'nombre' => 'Usuarios',
                'ruta' => 'users.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-users',
                'icono_r' => NULL,
                'orden' => 0,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 4,
                'option_id' => 2,
                'nombre' => 'Roles',
                'ruta' => 'roles.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-user-tag',
                'icono_r' => NULL,
                'orden' => 2,
                'color' => 'bg-info',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 5,
                'option_id' => 2,
                'nombre' => 'Permisos',
                'ruta' => 'permissions.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-key',
                'icono_r' => NULL,
                'orden' => 3,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 6,
                'option_id' => 2,
                'nombre' => 'Configuraciones',
                'ruta' => 'profile.business',
                'descripcion' => NULL,
                'icono_l' => 'fa-cogs',
                'icono_r' => NULL,
                'orden' => 4,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 7,
                'option_id' => NULL,
                'nombre' => 'Developer',
                'ruta' => 'x',
                'descripcion' => NULL,
                'icono_l' => 'fa-file-code',
                'icono_r' => NULL,
                'orden' => 25,
                'color' => '',
                'dev' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 8,
                'option_id' => 7,
                'nombre' => "Prueba API'S",
                'ruta' => 'dev.prueba.api',
                'descripcion' => NULL,
                'icono_l' => 'fa-check-circle',
                'icono_r' => NULL,
                'orden' => 21,
                'color' => '',
                'dev' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 9,
                'option_id' => 7,
                'nombre' => 'Configuraciones',
                'ruta' => 'dev.configurations.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-cogs',
                'icono_r' => NULL,
                'orden' => 20,
                'color' => '',
                'dev' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 10,
                'option_id' => 7,
                'nombre' => 'Clientes Passport',
                'ruta' => 'dev.passport.clients',
                'descripcion' => NULL,
                'icono_l' => 'fa-passport',
                'icono_r' => NULL,
                'orden' => 22,
                'color' => '',
                'dev' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 11,
                'option_id' => 7,
                'nombre' => 'Menu',
                'ruta' => 'options.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-list',
                'icono_r' => NULL,
                'orden' => 1,
                'color' => '',
                'dev' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 12,
                'option_id' => null,
                'nombre' => 'Clientes',
                'ruta' => 'clientes.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-people-roof',
                'icono_r' => NULL,
                'orden' => 25,
                'color' => '',
                'dev' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 13,
                'option_id' => null,
                'nombre' => 'Personas',
                'ruta' => 'personas.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-people-group',
                'icono_r' => NULL,
                'orden' => 25,
                'color' => '',
                'dev' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 14,
                'option_id' => null,
                'nombre' => 'Casos',
                'ruta' => 'casos.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-balance-scale',
                'icono_r' => NULL,
                'orden' => 25,
                'color' => '',
                'dev' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 15,
                'option_id' => null,
                'nombre' => 'Documentos',
                'ruta' => 'documentos.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-file-alt',
                'icono_r' => NULL,
                'orden' => 26,
                'color' => '',
                'dev' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 16,
                'option_id' => null,
                'nombre' => 'Audiencias',
                'ruta' => 'audiencias.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-calendar',
                'icono_r' => NULL,
                'orden' => 27,
                'color' => '',
                'dev' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 17,
                'option_id' => null,
                'nombre' => 'Tareas',
                'ruta' => 'tareas.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-clipboard-list',
                'icono_r' => NULL,
                'orden' => 28,
                'color' => '',
                'dev' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 18,
                'option_id' => null,
                'nombre' => 'Catálogos',
                'ruta' => '',
                'descripcion' => NULL,
                'icono_l' => 'fa-th-list',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 19,
                'option_id' => 18,
                'nombre' => 'Documentos',
                'ruta' => '',
                'descripcion' => NULL,
                'icono_l' => 'fa-folder-open',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 20,
                'option_id' => 19,
                'nombre' => 'Tipo',
                'ruta' => 'documentoTipos.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-tag',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 21,
                'option_id' => 19,
                'nombre' => 'Estados',
                'ruta' => 'documentoEstados.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-tag',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 22,
                'option_id' => 19,
                'nombre' => 'Tipo Escrituras',
                'ruta' => 'doctoPublicoEscrituras.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-tag',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 23,
                'option_id' => 19,
                'nombre' => 'Tipo Contratos',
                'ruta' => 'doctoPrivadoContratos.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-tag',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 24,
                'option_id' => 19,
                'nombre' => 'Tipo Acta Notarial',
                'ruta' => 'doctoActaNotarials.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-tag',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 25,
                'option_id' => 18,
                'nombre' => 'Casos',
                'ruta' => '',
                'descripcion' => NULL,
                'icono_l' => 'fa-folder-open',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 26,
                'option_id' => 25,
                'nombre' => 'Tipo',
                'ruta' => 'casoTipos.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-tag',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 27,
                'option_id' => 25,
                'nombre' => 'Tipos de Juicio',
                'ruta' => 'casoFamiliarJuicioTipos.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-tag',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 28,
                'option_id' => 25,
                'nombre' => 'Etapas de Juicios',
                'ruta' => 'casoFamiliarJuicioEtapas.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-tag',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 29,
                'option_id' => 25,
                'nombre' => 'Delitos',
                'ruta' => 'casoPenalDelitos.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-tag',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 30,
                'option_id' => 25,
                'nombre' => 'Etapas de Delitos',
                'ruta' => 'casoPenalEtapas.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-tag',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 31,
                'option_id' => 18,
                'nombre' => 'Tareas',
                'ruta' => '',
                'descripcion' => NULL,
                'icono_l' => 'fa-folder-open',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 32,
                'option_id' => 31,
                'nombre' => 'Estados',
                'ruta' => 'tareaEstados.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-tag',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
            [
                'id' => 33,
                'option_id' => 31,
                'nombre' => 'Prioridades',
                'ruta' => 'tareaPrioridads.index',
                'descripcion' => NULL,
                'icono_l' => 'fa-tag',
                'icono_r' => NULL,
                'orden' => 15,
                'color' => '',
                'dev' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => NULL,
            ],
        ]);


        $this->genraColoresIcons();

        \DB::statement('SET FOREIGN_KEY_CHECKS=1');

    }

    public function genraColoresIcons()
    {

        foreach (Option::all() as $index => $item) {

            $colores = [
                'text-indigo',
                'text-lightblue',
                'text-navy',
                'text-purple',
                'text-fuchsia',
                'text-pink',
                'text-maroon',
                'text-orange',
                'text-lime',
                'text-teal',
                'text-olive',
            ];

            $item->color = array_random($colores);
            $item->save();
        }

    }
}
